{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Box Loader Testing"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "I need to test a few things about the steps in the `argo_box_loader` notebook. There are a few things that might make a difference by decreasing the size of an array, but I want to try here on a box that takes a lot less time to load."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import xarray as xr\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "import argopy\n",
    "import scipy.ndimage as filter\n",
    "import scipy\n",
    "import matplotlib\n",
    "import gsw\n",
    "\n",
    "import argopy\n",
    "from argopy import DataFetcher as ArgoDataFetcher\n",
    "\n",
    "argo_loader = ArgoDataFetcher(\n",
    "    src=\"gdac\", ftp=\"/swot/SUM05/dbalwada/Argo_sync\", progress=True\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import sys\n",
    "os.chdir('/home.ufs/amf2288/argo-intern/funcs')\n",
    "sys.path.append(os.path.abspath('../funcs'))\n",
    "\n",
    "import processing_funcs as prf"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/node.py:187: UserWarning: Port 8787 is already in use.\n",
      "Perhaps you already have a cluster running?\n",
      "Hosting the HTTP server on port 41738 instead\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "LocalCluster(8aa8d6a2, 'tcp://127.0.0.1:36133', workers=64, threads=64, memory=0.98 TiB)\n"
     ]
    }
   ],
   "source": [
    "\"\"\"\n",
    "import dask\n",
    "from dask import delayed\n",
    "from dask.distributed import Client\n",
    "\n",
    "client = Client()\n",
    "\"\"\"\n",
    "\n",
    "from dask.distributed import Client, LocalCluster\n",
    "\n",
    "# Create a LocalCluster\n",
    "cluster = LocalCluster(n_workers=64, threads_per_worker=1)\n",
    "\n",
    "# Connect to the cluster\n",
    "client = Client(cluster)\n",
    "\n",
    "# Print the cluster information\n",
    "print(cluster)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "#box1 = [-180,-179,0,1,0,2001]\n",
    "box2 = [-180,-179,1,2,0,2001]\n",
    "box3 = [-180,-179,2,3,0,2001]\n",
    "box4 = [-180,-179,3,4,0,2001]\n",
    "box5 = [-180,-179,4,5,0,2001]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Example arguments for your function\n",
    "boxes_list = [\n",
    "    #(box1,2),\n",
    "    (box2),\n",
    "    (box3),\n",
    "    (box4),\n",
    "    (box5)\n",
    "]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "@dask.delayed\n",
    "def get_box_delayed(*args, **kwargs):\n",
    "    try:\n",
    "        return prf.get_box(*args, **kwargs)\n",
    "    except Exception as e:\n",
    "        return type(e).__name__, str(e)\n",
    "\n",
    "def get_box_dask(boxes_list, interp_step):\n",
    "    \n",
    "    boxes_list = [(box, interp_step) for box in boxes_list]\n",
    "    \n",
    "    # Create a list of delayed tasks\n",
    "    tasks = [get_box_delayed(*args) for args in boxes_list]\n",
    "\n",
    "    # Compute the results in parallel\n",
    "    results = dask.compute(*tasks)\n",
    "    \n",
    "    errors=[]\n",
    "\n",
    "    # Process the results as needed\n",
    "    for n, result in enumerate(results):\n",
    "        if isinstance(result, tuple) and isinstance(result[0], str):\n",
    "            error_type, error_message = result\n",
    "            print(\"Error in box {}: {} - {}\".format(boxes_list[n][0][0],boxes_list[n][0][1],boxes_list[n][0][2],boxes_list[n][0][3], error_type, error_message))\n",
    "            errors.append([boxes_list[n][0][0],boxes_list[n][0][1],boxes_list[n][0][2],boxes_list[n][0][3], error_type, error_message])\n",
    "        else:\n",
    "            result.to_netcdf(\"/swot/SUM05/amf2288/sync-boxes/atl_basin/lon:({},{})_lat:({},{})_ds_z.nc\".format(boxes_list[n][0][0],boxes_list[n][0][1],boxes_list[n][0][2],boxes_list[n][0][3]))\n",
    "            \n",
    "    return errors \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "#get_box_dask(boxes_list, 2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "from typing import List, Tuple\n",
    "\n",
    "#def generate_grid(min_lat: float, max_lat: float, min_lon: float, max_lon: float, step: float) -> List[Tuple[float, float, float, float]]:\n",
    "def generate_grid(box, step):\n",
    "    grid = []\n",
    "    lon_min, lon_max, lat_min, lat_max = box[0],box[1],box[2],box[3]\n",
    "    lat = lat_min\n",
    "    while lat < lat_max:\n",
    "        lon = lon_min\n",
    "        while lon < lon_max:\n",
    "            # Ensure the box does not exceed the specified bounds\n",
    "            box_lat_max = min(lat + step, lat_max)\n",
    "            box_lon_max = min(lon + step, lon_max)\n",
    "            box = [lat, box_lat_max, lon, box_lon_max, box[4], box[5]]\n",
    "            grid.append(box)\n",
    "            lon += step\n",
    "        lat += step\n",
    "    return grid"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[[0, 20, 0, 20, 0, 2001],\n",
       " [0, 20, 20, 40, 0, 2001],\n",
       " [0, 20, 40, 60, 0, 2001],\n",
       " [0, 20, 60, 80, 0, 2001],\n",
       " [0, 20, 80, 90, 0, 2001],\n",
       " [20, 40, 0, 20, 0, 2001],\n",
       " [20, 40, 20, 40, 0, 2001],\n",
       " [20, 40, 40, 60, 0, 2001],\n",
       " [20, 40, 60, 80, 0, 2001],\n",
       " [20, 40, 80, 90, 0, 2001],\n",
       " [40, 60, 0, 20, 0, 2001],\n",
       " [40, 60, 20, 40, 0, 2001],\n",
       " [40, 60, 40, 60, 0, 2001],\n",
       " [40, 60, 60, 80, 0, 2001],\n",
       " [40, 60, 80, 90, 0, 2001],\n",
       " [60, 80, 0, 20, 0, 2001],\n",
       " [60, 80, 20, 40, 0, 2001],\n",
       " [60, 80, 40, 60, 0, 2001],\n",
       " [60, 80, 60, 80, 0, 2001],\n",
       " [60, 80, 80, 90, 0, 2001],\n",
       " [80, 90, 0, 20, 0, 2001],\n",
       " [80, 90, 20, 40, 0, 2001],\n",
       " [80, 90, 40, 60, 0, 2001],\n",
       " [80, 90, 60, 80, 0, 2001],\n",
       " [80, 90, 80, 90, 0, 2001]]"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "generate_grid([0,90,0,90,0,2001], 20)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[[0, 5, 0, 5, 0, 2001],\n",
       " [0, 5, 5, 10, 0, 2001],\n",
       " [0, 5, 10, 15, 0, 2001],\n",
       " [0, 5, 15, 20, 0, 2001],\n",
       " [5, 10, 0, 5, 0, 2001],\n",
       " [5, 10, 5, 10, 0, 2001],\n",
       " [5, 10, 10, 15, 0, 2001],\n",
       " [5, 10, 15, 20, 0, 2001],\n",
       " [10, 15, 0, 5, 0, 2001],\n",
       " [10, 15, 5, 10, 0, 2001],\n",
       " [10, 15, 10, 15, 0, 2001],\n",
       " [10, 15, 15, 20, 0, 2001],\n",
       " [15, 20, 0, 5, 0, 2001],\n",
       " [15, 20, 5, 10, 0, 2001],\n",
       " [15, 20, 10, 15, 0, 2001],\n",
       " [15, 20, 15, 20, 0, 2001]]"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "generate_grid([0,20,0,20,0,2001], 5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Process Dask Worker process (from Nanny):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 686, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/nanny.py\", line 984, in run\n",
      "    await worker.finished()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/core.py\", line 491, in finished\n",
      "    await self._event_finished.wait()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/locks.py\", line 212, in wait\n",
      "    await fut\n",
      "asyncio.exceptions.CancelledError\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/nanny.py\", line 1022, in _run\n",
      "    asyncio_run(run(), loop_factory=get_loop_factory())\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 194, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 123, in run\n",
      "    raise KeyboardInterrupt()\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/process.py\", line 202, in _run\n",
      "    target(*args, **kwargs)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/nanny.py\", line 996, in _run\n",
      "    with contextlib.ExitStack() as stack:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/contextlib.py\", line 610, in __exit__\n",
      "    raise exc_details[1]\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/contextlib.py\", line 595, in __exit__\n",
      "    if cb(*exc_details):\n",
      "       ^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/contextlib.py\", line 478, in _exit_wrapper\n",
      "    callback(*args, **kwds)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/threading.py\", line 1153, in join\n",
      "    self._wait_for_tstate_lock(timeout=max(timeout, 0))\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/threading.py\", line 1169, in _wait_for_tstate_lock\n",
      "    if lock.acquire(block, timeout):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "KeyboardInterrupt\n",
      "2025-01-03 09:09:47,799 - distributed.worker - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 194, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 673, in run_until_complete\n",
      "    self.run_forever()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 640, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 1954, in _run_once\n",
      "    event_list = self._selector.select(timeout)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/selectors.py\", line 468, in select\n",
      "    fd_event_list = self._selector.poll(timeout, max_ev)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 157, in _on_sigint\n",
      "    raise KeyboardInterrupt()\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/utils.py\", line 806, in wrapper\n",
      "    return await func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/worker.py\", line 1639, in close\n",
      "    await asyncio.to_thread(\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/threads.py\", line 25, in to_thread\n",
      "    return await loop.run_in_executor(None, func_call)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "asyncio.exceptions.CancelledError\n",
      "2025-01-03 09:09:47,803 - distributed.worker - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 194, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 673, in run_until_complete\n",
      "    self.run_forever()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 640, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 1954, in _run_once\n",
      "    event_list = self._selector.select(timeout)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/selectors.py\", line 468, in select\n",
      "    fd_event_list = self._selector.poll(timeout, max_ev)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 157, in _on_sigint\n",
      "    raise KeyboardInterrupt()\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/utils.py\", line 806, in wrapper\n",
      "    return await func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/worker.py\", line 1521, in close\n",
      "    await self.finished()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/core.py\", line 491, in finished\n",
      "    await self._event_finished.wait()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/locks.py\", line 212, in wait\n",
      "    await fut\n",
      "asyncio.exceptions.CancelledError\n",
      "2025-01-03 09:09:47,811 - distributed.worker - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 194, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 673, in run_until_complete\n",
      "    self.run_forever()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 640, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 1954, in _run_once\n",
      "    event_list = self._selector.select(timeout)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/selectors.py\", line 468, in select\n",
      "    fd_event_list = self._selector.poll(timeout, max_ev)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 157, in _on_sigint\n",
      "    raise KeyboardInterrupt()\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/utils.py\", line 806, in wrapper\n",
      "    return await func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/worker.py\", line 1639, in close\n",
      "    await asyncio.to_thread(\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/threads.py\", line 25, in to_thread\n",
      "    return await loop.run_in_executor(None, func_call)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "asyncio.exceptions.CancelledError\n",
      "2025-01-03 09:09:47,817 - distributed.worker - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 194, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 673, in run_until_complete\n",
      "    self.run_forever()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 640, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 1954, in _run_once\n",
      "    event_list = self._selector.select(timeout)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/selectors.py\", line 468, in select\n",
      "    fd_event_list = self._selector.poll(timeout, max_ev)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 157, in _on_sigint\n",
      "    raise KeyboardInterrupt()\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/utils.py\", line 806, in wrapper\n",
      "    return await func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/worker.py\", line 1639, in close\n",
      "    await asyncio.to_thread(\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/threads.py\", line 25, in to_thread\n",
      "    return await loop.run_in_executor(None, func_call)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "asyncio.exceptions.CancelledError\n",
      "2025-01-03 09:09:47,882 - distributed.worker - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 194, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 673, in run_until_complete\n",
      "    self.run_forever()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 640, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 1954, in _run_once\n",
      "    event_list = self._selector.select(timeout)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/selectors.py\", line 468, in select\n",
      "    fd_event_list = self._selector.poll(timeout, max_ev)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 157, in _on_sigint\n",
      "    raise KeyboardInterrupt()\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/utils.py\", line 806, in wrapper\n",
      "    return await func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/worker.py\", line 1521, in close\n",
      "    await self.finished()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/core.py\", line 491, in finished\n",
      "    await self._event_finished.wait()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/locks.py\", line 212, in wait\n",
      "    await fut\n",
      "asyncio.exceptions.CancelledError\n",
      "2025-01-03 09:09:47,889 - distributed.worker - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 194, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 673, in run_until_complete\n",
      "    self.run_forever()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 640, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 1954, in _run_once\n",
      "    event_list = self._selector.select(timeout)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/selectors.py\", line 468, in select\n",
      "    fd_event_list = self._selector.poll(timeout, max_ev)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 157, in _on_sigint\n",
      "    raise KeyboardInterrupt()\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/utils.py\", line 806, in wrapper\n",
      "    return await func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/worker.py\", line 1639, in close\n",
      "    await asyncio.to_thread(\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/threads.py\", line 25, in to_thread\n",
      "    return await loop.run_in_executor(None, func_call)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "asyncio.exceptions.CancelledError\n",
      "2025-01-03 09:09:47,877 - distributed.worker - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 194, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 673, in run_until_complete\n",
      "    self.run_forever()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 640, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 1992, in _run_once\n",
      "    handle._run()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/tornado/platform/asyncio.py\", line 202, in _handle_events\n",
      "    handler_func(fileobj, events)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/tornado/iostream.py\", line 691, in _handle_events\n",
      "    self._handle_read()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/tornado/iostream.py\", line 773, in _handle_read\n",
      "    pos = self._read_to_buffer_loop()\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/tornado/iostream.py\", line 750, in _read_to_buffer_loop\n",
      "    if self._read_to_buffer() == 0:\n",
      "       ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/tornado/iostream.py\", line 861, in _read_to_buffer\n",
      "    bytes_read = self.read_from_fd(buf)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/tornado/iostream.py\", line 1116, in read_from_fd\n",
      "    return self.socket.recv_into(buf, len(buf))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 157, in _on_sigint\n",
      "    raise KeyboardInterrupt()\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/utils.py\", line 806, in wrapper\n",
      "    return await func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/worker.py\", line 1558, in close\n",
      "    await r.close_gracefully(reason=reason)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/core.py\", line 1253, in send_recv_from_rpc\n",
      "    comm = await self.pool.connect(self.addr)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/core.py\", line 1481, in connect\n",
      "    return await self._connect(addr=addr, timeout=timeout)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/core.py\", line 1425, in _connect\n",
      "    comm = await connect(\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/comm/core.py\", line 342, in connect\n",
      "    comm = await wait_for(\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/utils.py\", line 1921, in wait_for\n",
      "    return await fut\n",
      "           ^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/comm/tcp.py\", line 546, in connect\n",
      "    stream = await self.client.connect(\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/tornado/tcpclient.py\", line 279, in connect\n",
      "    af, addr, stream = await connector.start(connect_timeout=timeout)\n",
      "                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "asyncio.exceptions.CancelledError\n",
      "2025-01-03 09:09:47,942 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name=\"execute('get_box_delayed-a2b10f5e-bc05-4d73-ad12-a1dda7d06171')\" coro=<Worker.execute() done, defined at /home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/worker_state_machine.py:3609>> ended with CancelledError\n",
      "2025-01-03 09:09:47,942 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name=\"execute('get_box_delayed-7aa8d5e9-4272-4277-998a-9a6462f53e8e')\" coro=<Worker.execute() done, defined at /home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/worker_state_machine.py:3609>> ended with CancelledError\n",
      "2025-01-03 09:09:47,943 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name=\"execute('get_box_delayed-3975d0e4-6ebb-47d7-89d6-eb719b28d543')\" coro=<Worker.execute() done, defined at /home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/worker_state_machine.py:3609>> ended with CancelledError\n",
      "2025-01-03 09:09:47,943 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name=\"execute('get_box_delayed-ce0cfd6d-d642-4bae-99e8-ea13e15f0331')\" coro=<Worker.execute() done, defined at /home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/worker_state_machine.py:3609>> ended with CancelledError\n",
      "2025-01-03 09:09:47,943 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name=\"execute('get_box_delayed-177e4d12-bcb0-4751-8a08-513cc30ff31d')\" coro=<Worker.execute() done, defined at /home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/worker_state_machine.py:3609>> ended with CancelledError\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "to xarray complete\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-01-03 09:09:47,916 - distributed.worker - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/nanny.py\", line 984, in run\n",
      "    await worker.finished()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/core.py\", line 491, in finished\n",
      "    await self._event_finished.wait()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/locks.py\", line 212, in wait\n",
      "    await fut\n",
      "asyncio.exceptions.CancelledError\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/utils.py\", line 806, in wrapper\n",
      "    return await func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/worker.py\", line 1558, in close\n",
      "    await r.close_gracefully(reason=reason)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/core.py\", line 1253, in send_recv_from_rpc\n",
      "    comm = await self.pool.connect(self.addr)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/core.py\", line 1481, in connect\n",
      "    return await self._connect(addr=addr, timeout=timeout)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/core.py\", line 1425, in _connect\n",
      "    comm = await connect(\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/comm/core.py\", line 342, in connect\n",
      "    comm = await wait_for(\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/utils.py\", line 1921, in wait_for\n",
      "    return await fut\n",
      "           ^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/comm/tcp.py\", line 546, in connect\n",
      "    stream = await self.client.connect(\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/tornado/tcpclient.py\", line 269, in connect\n",
      "    addrinfo = await self.resolver.resolve(host, port, af)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/comm/tcp.py\", line 524, in resolve\n",
      "    for fam, _, _, _, address in await _getaddrinfo(\n",
      "                                 ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/comm/tcp.py\", line 484, in _getaddrinfo\n",
      "    return socket.getaddrinfo(\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/socket.py\", line 976, in getaddrinfo\n",
      "    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 157, in _on_sigint\n",
      "    raise KeyboardInterrupt()\n",
      "KeyboardInterrupt\n",
      "2025-01-03 09:09:47,959 - distributed.worker - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 194, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 673, in run_until_complete\n",
      "    self.run_forever()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 640, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 1954, in _run_once\n",
      "    event_list = self._selector.select(timeout)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/selectors.py\", line 468, in select\n",
      "    fd_event_list = self._selector.poll(timeout, max_ev)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 157, in _on_sigint\n",
      "    raise KeyboardInterrupt()\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/utils.py\", line 806, in wrapper\n",
      "    return await func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/worker.py\", line 1521, in close\n",
      "    await self.finished()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/core.py\", line 491, in finished\n",
      "    await self._event_finished.wait()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/locks.py\", line 212, in wait\n",
      "    await fut\n",
      "asyncio.exceptions.CancelledError\n",
      "2025-01-03 09:09:47,926 - distributed.worker - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 194, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 673, in run_until_complete\n",
      "    self.run_forever()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 640, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 1954, in _run_once\n",
      "    event_list = self._selector.select(timeout)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/selectors.py\", line 468, in select\n",
      "    fd_event_list = self._selector.poll(timeout, max_ev)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 157, in _on_sigint\n",
      "    raise KeyboardInterrupt()\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/utils.py\", line 806, in wrapper\n",
      "    return await func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/worker.py\", line 1521, in close\n",
      "    await self.finished()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/core.py\", line 491, in finished\n",
      "    await self._event_finished.wait()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/locks.py\", line 212, in wait\n",
      "    await fut\n",
      "asyncio.exceptions.CancelledError\n",
      "Process Dask Worker process (from Nanny):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 194, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 673, in run_until_complete\n",
      "    self.run_forever()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 640, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 1992, in _run_once\n",
      "    handle._run()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/tornado/platform/asyncio.py\", line 202, in _handle_events\n",
      "    handler_func(fileobj, events)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/tornado/iostream.py\", line 691, in _handle_events\n",
      "    self._handle_read()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/tornado/iostream.py\", line 773, in _handle_read\n",
      "    pos = self._read_to_buffer_loop()\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/tornado/iostream.py\", line 750, in _read_to_buffer_loop\n",
      "    if self._read_to_buffer() == 0:\n",
      "       ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/tornado/iostream.py\", line 861, in _read_to_buffer\n",
      "    bytes_read = self.read_from_fd(buf)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/tornado/iostream.py\", line 1116, in read_from_fd\n",
      "    return self.socket.recv_into(buf, len(buf))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 157, in _on_sigint\n",
      "    raise KeyboardInterrupt()\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/nanny.py\", line 1022, in _run\n",
      "    asyncio_run(run(), loop_factory=get_loop_factory())\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 193, in run\n",
      "    with Runner(debug=debug, loop_factory=loop_factory) as runner:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 62, in __exit__\n",
      "    self.close()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 70, in close\n",
      "    _cancel_all_tasks(loop)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 205, in _cancel_all_tasks\n",
      "    loop.run_until_complete(tasks.gather(*to_cancel, return_exceptions=True))\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 673, in run_until_complete\n",
      "    self.run_forever()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 640, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 1992, in _run_once\n",
      "    handle._run()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/tornado/ioloop.py\", line 937, in _run\n",
      "    val = self.callback()\n",
      "          ^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/system_monitor.py\", line 179, in update\n",
      "    disk_ioc = psutil.disk_io_counters()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/psutil/__init__.py\", line 2109, in disk_io_counters\n",
      "    rawdict = _psplatform.disk_io_counters(**kwargs)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/psutil/_pslinux.py\", line 1235, in disk_io_counters\n",
      "    if not perdisk and not is_storage_device(name):\n",
      "                           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/psutil/_pslinux.py\", line 261, in is_storage_device\n",
      "    return os.access(path, os.F_OK)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/process.py\", line 202, in _run\n",
      "    target(*args, **kwargs)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/nanny.py\", line 996, in _run\n",
      "    with contextlib.ExitStack() as stack:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/contextlib.py\", line 610, in __exit__\n",
      "    raise exc_details[1]\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/contextlib.py\", line 595, in __exit__\n",
      "    if cb(*exc_details):\n",
      "       ^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/contextlib.py\", line 478, in _exit_wrapper\n",
      "    callback(*args, **kwds)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/threading.py\", line 1153, in join\n",
      "    self._wait_for_tstate_lock(timeout=max(timeout, 0))\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/threading.py\", line 1169, in _wait_for_tstate_lock\n",
      "    if lock.acquire(block, timeout):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "KeyboardInterrupt\n",
      "Process Dask Worker process (from Nanny):\n",
      "Process Dask Worker process (from Nanny):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 194, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 673, in run_until_complete\n",
      "    self.run_forever()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 640, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 1954, in _run_once\n",
      "    event_list = self._selector.select(timeout)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/selectors.py\", line 468, in select\n",
      "    fd_event_list = self._selector.poll(timeout, max_ev)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 157, in _on_sigint\n",
      "    raise KeyboardInterrupt()\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/nanny.py\", line 1022, in _run\n",
      "    asyncio_run(run(), loop_factory=get_loop_factory())\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 193, in run\n",
      "    with Runner(debug=debug, loop_factory=loop_factory) as runner:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 62, in __exit__\n",
      "    self.close()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 72, in close\n",
      "    loop.run_until_complete(\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 673, in run_until_complete\n",
      "    self.run_forever()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 640, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 1954, in _run_once\n",
      "    event_list = self._selector.select(timeout)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/selectors.py\", line 468, in select\n",
      "    fd_event_list = self._selector.poll(timeout, max_ev)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/process.py\", line 202, in _run\n",
      "    target(*args, **kwargs)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/nanny.py\", line 996, in _run\n",
      "    with contextlib.ExitStack() as stack:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/contextlib.py\", line 610, in __exit__\n",
      "    raise exc_details[1]\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/contextlib.py\", line 595, in __exit__\n",
      "    if cb(*exc_details):\n",
      "       ^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/contextlib.py\", line 478, in _exit_wrapper\n",
      "    callback(*args, **kwds)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/threading.py\", line 1153, in join\n",
      "    self._wait_for_tstate_lock(timeout=max(timeout, 0))\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/threading.py\", line 1169, in _wait_for_tstate_lock\n",
      "    if lock.acquire(block, timeout):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "KeyboardInterrupt\n",
      "2025-01-03 09:09:48,103 - distributed.nanny - ERROR - Worker process died unexpectedly\n",
      "Process Dask Worker process (from Nanny):\n",
      "2025-01-03 09:09:48,106 - distributed.nanny - ERROR - Worker process died unexpectedly\n",
      "Process Dask Worker process (from Nanny):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 194, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 673, in run_until_complete\n",
      "    self.run_forever()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 640, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 1954, in _run_once\n",
      "    event_list = self._selector.select(timeout)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/selectors.py\", line 468, in select\n",
      "    fd_event_list = self._selector.poll(timeout, max_ev)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 157, in _on_sigint\n",
      "    raise KeyboardInterrupt()\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/nanny.py\", line 1022, in _run\n",
      "    asyncio_run(run(), loop_factory=get_loop_factory())\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 193, in run\n",
      "    with Runner(debug=debug, loop_factory=loop_factory) as runner:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 62, in __exit__\n",
      "    self.close()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 72, in close\n",
      "    loop.run_until_complete(\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 673, in run_until_complete\n",
      "    self.run_forever()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 640, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 1954, in _run_once\n",
      "    event_list = self._selector.select(timeout)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/selectors.py\", line 468, in select\n",
      "    fd_event_list = self._selector.poll(timeout, max_ev)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "Process Dask Worker process (from Nanny):\n",
      "Traceback (most recent call last):\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 194, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 673, in run_until_complete\n",
      "    self.run_forever()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 640, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/process.py\", line 202, in _run\n",
      "    target(*args, **kwargs)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 1954, in _run_once\n",
      "    event_list = self._selector.select(timeout)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/nanny.py\", line 996, in _run\n",
      "    with contextlib.ExitStack() as stack:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/selectors.py\", line 468, in select\n",
      "    fd_event_list = self._selector.poll(timeout, max_ev)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/contextlib.py\", line 610, in __exit__\n",
      "    raise exc_details[1]\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 157, in _on_sigint\n",
      "    raise KeyboardInterrupt()\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/nanny.py\", line 1022, in _run\n",
      "    asyncio_run(run(), loop_factory=get_loop_factory())\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 193, in run\n",
      "    with Runner(debug=debug, loop_factory=loop_factory) as runner:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 62, in __exit__\n",
      "    self.close()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 72, in close\n",
      "    loop.run_until_complete(\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 673, in run_until_complete\n",
      "    self.run_forever()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 640, in run_forever\n",
      "    self._run_once()\n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 1954, in _run_once\n",
      "    event_list = self._selector.select(timeout)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/selectors.py\", line 468, in select\n",
      "    fd_event_list = self._selector.poll(timeout, max_ev)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/process.py\", line 202, in _run\n",
      "    target(*args, **kwargs)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/nanny.py\", line 996, in _run\n",
      "    with contextlib.ExitStack() as stack:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/contextlib.py\", line 610, in __exit__\n",
      "    raise exc_details[1]\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/contextlib.py\", line 595, in __exit__\n",
      "    if cb(*exc_details):\n",
      "       ^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/contextlib.py\", line 478, in _exit_wrapper\n",
      "    callback(*args, **kwds)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/threading.py\", line 1153, in join\n",
      "    self._wait_for_tstate_lock(timeout=max(timeout, 0))\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/threading.py\", line 1169, in _wait_for_tstate_lock\n",
      "    if lock.acquire(block, timeout):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "KeyboardInterrupt\n",
      "Process Dask Worker process (from Nanny):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/contextlib.py\", line 595, in __exit__\n",
      "    if cb(*exc_details):\n",
      "       ^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/contextlib.py\", line 478, in _exit_wrapper\n",
      "    callback(*args, **kwds)\n",
      "2025-01-03 09:09:48,201 - distributed.nanny - ERROR - Worker process died unexpectedly\n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 194, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 673, in run_until_complete\n",
      "    self.run_forever()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 640, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 1954, in _run_once\n",
      "    event_list = self._selector.select(timeout)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/selectors.py\", line 468, in select\n",
      "    fd_event_list = self._selector.poll(timeout, max_ev)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/threading.py\", line 1153, in join\n",
      "    self._wait_for_tstate_lock(timeout=max(timeout, 0))\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/threading.py\", line 1169, in _wait_for_tstate_lock\n",
      "    if lock.acquire(block, timeout):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "KeyboardInterrupt\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 157, in _on_sigint\n",
      "    raise KeyboardInterrupt()\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/nanny.py\", line 1022, in _run\n",
      "    asyncio_run(run(), loop_factory=get_loop_factory())\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 193, in run\n",
      "    with Runner(debug=debug, loop_factory=loop_factory) as runner:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 62, in __exit__\n",
      "    self.close()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/nanny.py\", line 984, in run\n",
      "    await worker.finished()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/core.py\", line 491, in finished\n",
      "    await self._event_finished.wait()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/locks.py\", line 212, in wait\n",
      "    await fut\n",
      "asyncio.exceptions.CancelledError\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 72, in close\n",
      "    loop.run_until_complete(\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 673, in run_until_complete\n",
      "    self.run_forever()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 640, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/nanny.py\", line 1022, in _run\n",
      "    asyncio_run(run(), loop_factory=get_loop_factory())\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 193, in run\n",
      "    with Runner(debug=debug, loop_factory=loop_factory) as runner:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 62, in __exit__\n",
      "    self.close()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 70, in close\n",
      "    _cancel_all_tasks(loop)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 205, in _cancel_all_tasks\n",
      "    loop.run_until_complete(tasks.gather(*to_cancel, return_exceptions=True))\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 673, in run_until_complete\n",
      "    self.run_forever()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 640, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 1992, in _run_once\n",
      "    handle._run()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/nanny.py\", line 968, in run\n",
      "    async with worker:\n",
      "               ^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/core.py\", line 543, in __aexit__\n",
      "    await self.close()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 1954, in _run_once\n",
      "    event_list = self._selector.select(timeout)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/selectors.py\", line 468, in select\n",
      "    fd_event_list = self._selector.poll(timeout, max_ev)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/process.py\", line 202, in _run\n",
      "    target(*args, **kwargs)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/nanny.py\", line 996, in _run\n",
      "    with contextlib.ExitStack() as stack:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/contextlib.py\", line 610, in __exit__\n",
      "    raise exc_details[1]\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/contextlib.py\", line 595, in __exit__\n",
      "    if cb(*exc_details):\n",
      "       ^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/utils.py\", line 805, in wrapper\n",
      "    with self:\n",
      "         ^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/contextlib.py\", line 478, in _exit_wrapper\n",
      "    callback(*args, **kwds)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/threading.py\", line 1153, in join\n",
      "    self._wait_for_tstate_lock(timeout=max(timeout, 0))\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/threading.py\", line 1169, in _wait_for_tstate_lock\n",
      "    if lock.acquire(block, timeout):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "KeyboardInterrupt\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/utils.py\", line 831, in __exit__\n",
      "    logger.exception(exc_value)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/logging/__init__.py\", line 1574, in exception\n",
      "    self.error(msg, *args, exc_info=exc_info, **kwargs)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/logging/__init__.py\", line 1568, in error\n",
      "    self._log(ERROR, msg, args, **kwargs)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/logging/__init__.py\", line 1684, in _log\n",
      "    self.handle(record)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/logging/__init__.py\", line 1700, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/logging/__init__.py\", line 1762, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/logging/__init__.py\", line 1028, in handle\n",
      "    self.emit(record)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/logging/__init__.py\", line 1160, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/logging/__init__.py\", line 999, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/logging/__init__.py\", line 711, in format\n",
      "    record.exc_text = self.formatException(record.exc_info)\n",
      "                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/logging/__init__.py\", line 661, in formatException\n",
      "    traceback.print_exception(ei[0], ei[1], tb, None, sio)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/traceback.py\", line 124, in print_exception\n",
      "    te = TracebackException(type(value), value, tb, limit=limit, compact=True)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/traceback.py\", line 733, in __init__\n",
      "    self.stack = StackSummary._extract_from_extended_frame_gen(\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/traceback.py\", line 434, in _extract_from_extended_frame_gen\n",
      "    linecache.checkcache(filename)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/linecache.py\", line 72, in checkcache\n",
      "    stat = os.stat(fullname)\n",
      "           ^^^^^^^^^^^^^^^^^\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/process.py\", line 202, in _run\n",
      "    target(*args, **kwargs)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/nanny.py\", line 996, in _run\n",
      "    with contextlib.ExitStack() as stack:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/contextlib.py\", line 610, in __exit__\n",
      "    raise exc_details[1]\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/contextlib.py\", line 595, in __exit__\n",
      "    if cb(*exc_details):\n",
      "       ^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/contextlib.py\", line 478, in _exit_wrapper\n",
      "    callback(*args, **kwds)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/threading.py\", line 1153, in join\n",
      "    self._wait_for_tstate_lock(timeout=max(timeout, 0))\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/threading.py\", line 1169, in _wait_for_tstate_lock\n",
      "    if lock.acquire(block, timeout):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "KeyboardInterrupt\n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/nanny.py\", line 984, in run\n",
      "    await worker.finished()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/core.py\", line 491, in finished\n",
      "    await self._event_finished.wait()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/locks.py\", line 212, in wait\n",
      "    await fut\n",
      "asyncio.exceptions.CancelledError\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/nanny.py\", line 1022, in _run\n",
      "    asyncio_run(run(), loop_factory=get_loop_factory())\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 193, in run\n",
      "    with Runner(debug=debug, loop_factory=loop_factory) as runner:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 62, in __exit__\n",
      "    self.close()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 70, in close\n",
      "    _cancel_all_tasks(loop)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 205, in _cancel_all_tasks\n",
      "    loop.run_until_complete(tasks.gather(*to_cancel, return_exceptions=True))\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 673, in run_until_complete\n",
      "    self.run_forever()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 640, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 1992, in _run_once\n",
      "    handle._run()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/nanny.py\", line 968, in run\n",
      "    async with worker:\n",
      "               ^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/core.py\", line 543, in __aexit__\n",
      "    await self.close()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/utils.py\", line 805, in wrapper\n",
      "    with self:\n",
      "         ^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/utils.py\", line 831, in __exit__\n",
      "    logger.exception(exc_value)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/logging/__init__.py\", line 1574, in exception\n",
      "    self.error(msg, *args, exc_info=exc_info, **kwargs)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/logging/__init__.py\", line 1568, in error\n",
      "    self._log(ERROR, msg, args, **kwargs)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/logging/__init__.py\", line 1684, in _log\n",
      "    self.handle(record)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/logging/__init__.py\", line 1700, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/logging/__init__.py\", line 1762, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/logging/__init__.py\", line 1028, in handle\n",
      "    self.emit(record)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/logging/__init__.py\", line 1160, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/logging/__init__.py\", line 999, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/logging/__init__.py\", line 711, in format\n",
      "    record.exc_text = self.formatException(record.exc_info)\n",
      "                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/logging/__init__.py\", line 661, in formatException\n",
      "    traceback.print_exception(ei[0], ei[1], tb, None, sio)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/traceback.py\", line 124, in print_exception\n",
      "    te = TracebackException(type(value), value, tb, limit=limit, compact=True)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/traceback.py\", line 811, in __init__\n",
      "    context = TracebackException(\n",
      "              ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/traceback.py\", line 733, in __init__\n",
      "    self.stack = StackSummary._extract_from_extended_frame_gen(\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/traceback.py\", line 438, in _extract_from_extended_frame_gen\n",
      "    f.line\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/traceback.py\", line 323, in line\n",
      "    self._line = linecache.getline(self.filename, self.lineno)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/linecache.py\", line 30, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/linecache.py\", line 46, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/linecache.py\", line 139, in updatecache\n",
      "    lines = fp.readlines()\n",
      "            ^^^^^^^^^^^^^^\n",
      "  File \"<frozen codecs>\", line 319, in decode\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/process.py\", line 202, in _run\n",
      "    target(*args, **kwargs)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/nanny.py\", line 996, in _run\n",
      "    with contextlib.ExitStack() as stack:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/contextlib.py\", line 610, in __exit__\n",
      "    raise exc_details[1]\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/contextlib.py\", line 595, in __exit__\n",
      "    if cb(*exc_details):\n",
      "       ^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/contextlib.py\", line 478, in _exit_wrapper\n",
      "    callback(*args, **kwds)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/threading.py\", line 1153, in join\n",
      "    self._wait_for_tstate_lock(timeout=max(timeout, 0))\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/threading.py\", line 1169, in _wait_for_tstate_lock\n",
      "    if lock.acquire(block, timeout):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "KeyboardInterrupt\n",
      "Process Dask Worker process (from Nanny):\n",
      "2025-01-03 09:09:50,102 - distributed.nanny - ERROR - Worker process died unexpectedly\n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/nanny.py\", line 984, in run\n",
      "    await worker.finished()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/core.py\", line 491, in finished\n",
      "    await self._event_finished.wait()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/locks.py\", line 212, in wait\n",
      "    await fut\n",
      "asyncio.exceptions.CancelledError\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 194, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 673, in run_until_complete\n",
      "    self.run_forever()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 640, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 1992, in _run_once\n",
      "    handle._run()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/nanny.py\", line 968, in run\n",
      "    async with worker:\n",
      "               ^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/core.py\", line 543, in __aexit__\n",
      "    await self.close()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/utils.py\", line 806, in wrapper\n",
      "    return await func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/worker.py\", line 1558, in close\n",
      "    await r.close_gracefully(reason=reason)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/core.py\", line 1253, in send_recv_from_rpc\n",
      "    comm = await self.pool.connect(self.addr)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/core.py\", line 1481, in connect\n",
      "    return await self._connect(addr=addr, timeout=timeout)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/core.py\", line 1425, in _connect\n",
      "    comm = await connect(\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/comm/core.py\", line 342, in connect\n",
      "    comm = await wait_for(\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/utils.py\", line 1921, in wait_for\n",
      "    return await fut\n",
      "           ^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/comm/tcp.py\", line 546, in connect\n",
      "    stream = await self.client.connect(\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/tornado/tcpclient.py\", line 269, in connect\n",
      "    addrinfo = await self.resolver.resolve(host, port, af)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/comm/tcp.py\", line 524, in resolve\n",
      "    for fam, _, _, _, address in await _getaddrinfo(\n",
      "                                 ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/comm/tcp.py\", line 484, in _getaddrinfo\n",
      "    return socket.getaddrinfo(\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/socket.py\", line 976, in getaddrinfo\n",
      "    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 157, in _on_sigint\n",
      "    raise KeyboardInterrupt()\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 70, in close\n",
      "    _cancel_all_tasks(loop)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 205, in _cancel_all_tasks\n",
      "    loop.run_until_complete(tasks.gather(*to_cancel, return_exceptions=True))\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 673, in run_until_complete\n",
      "    self.run_forever()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 640, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/base_events.py\", line 1992, in _run_once\n",
      "    handle._run()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/tornado/ioloop.py\", line 939, in _run\n",
      "    await val\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/worker.py\", line 1250, in heartbeat\n",
      "    response = await retry_operation(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/utils_comm.py\", line 461, in retry_operation\n",
      "    return await retry(\n",
      "           ^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/utils_comm.py\", line 440, in retry\n",
      "    return await coro()\n",
      "           ^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/core.py\", line 1256, in send_recv_from_rpc\n",
      "    return await send_recv(comm=comm, op=key, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/core.py\", line 1015, in send_recv\n",
      "    response = await comm.read(deserializers=deserializers)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/comm/tcp.py\", line 225, in read\n",
      "    frames_nosplit_nbytes_bin = await stream.read_bytes(fmt_size)\n",
      "                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/tornado/iostream.py\", line 422, in read_bytes\n",
      "    self._try_inline_read()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/tornado/iostream.py\", line 836, in _try_inline_read\n",
      "    pos = self._read_to_buffer_loop()\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/tornado/iostream.py\", line 769, in _read_to_buffer_loop\n",
      "    return self._find_read_pos()\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/tornado/iostream.py\", line 901, in _find_read_pos\n",
      "    def _find_read_pos(self) -> Optional[int]:\n",
      "    \n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/process.py\", line 202, in _run\n",
      "    target(*args, **kwargs)\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/nanny.py\", line 1022, in _run\n",
      "    asyncio_run(run(), loop_factory=get_loop_factory())\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 193, in run\n",
      "    with Runner(debug=debug, loop_factory=loop_factory) as runner:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 62, in __exit__\n",
      "    self.close()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/runners.py\", line 77, in close\n",
      "    loop.close()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/unix_events.py\", line 68, in close\n",
      "    super().close()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/selector_events.py\", line 104, in close\n",
      "    self._close_self_pipe()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/asyncio/selector_events.py\", line 114, in _close_self_pipe\n",
      "    self._csock.close()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/socket.py\", line 505, in close\n",
      "    self._real_close()\n",
      "  File \"/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/socket.py\", line 499, in _real_close\n",
      "    _ss.close(self)\n",
      "KeyboardInterrupt\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "to xarray complete\n",
      "point to profile complete\n",
      "interpolation complete\n",
      "adding spice complete\n",
      "adding MLD complete\n",
      "to xarray complete\n",
      "point to profile complete\n",
      "interpolation complete\n",
      "adding spice complete\n",
      "adding MLD complete\n"
     ]
    }
   ],
   "source": [
    "def get_target_box(area, region_step, target_step, interp_step):\n",
    "    \n",
    "    regions = generate_grid(area, region_step)\n",
    "    print('-' * 50)\n",
    "    print(\"THE REGIONS ARE {}\".format(regions))\n",
    "    \n",
    "    errors_list = []\n",
    "    \n",
    "    for n,region in enumerate(regions):\n",
    "        boxes = generate_grid(region, target_step)\n",
    "        print('-' * 50)\n",
    "        print(\"REGION #1{} IS: {}\".format(n+1, region))\n",
    "        print('-' * 50)\n",
    "        print(\"THE BOXES IN REGION #{} ARE {}\".format(n+1,boxes))\n",
    "        print('-' * 50)\n",
    "\n",
    "        errors = get_box_dask(boxes, interp_step)\n",
    "        errors_list.append([errors])\n",
    "        \n",
    "        print('-' * 50)\n",
    "        print(\"COMPLETED REGION #{} OUT OF {}\".format(n+1,len(regions)))\n",
    "        print('-' * 50)\n",
    "        \n",
    "    return errors_list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "------------------------------\n",
      "THE REGIONS ARE [[-90, -50, -75, -35, 0, 2000], [-90, -50, -35, 5, 0, 2000], [-90, -50, 5, 25, 0, 2000], [-50, -10, -75, -35, 0, 2000], [-50, -10, -35, 5, 0, 2000], [-50, -10, 5, 25, 0, 2000], [-10, 30, -75, -35, 0, 2000], [-10, 30, -35, 5, 0, 2000], [-10, 30, 5, 25, 0, 2000], [30, 70, -75, -35, 0, 2000], [30, 70, -35, 5, 0, 2000], [30, 70, 5, 25, 0, 2000], [70, 90, -75, -35, 0, 2000], [70, 90, -35, 5, 0, 2000], [70, 90, 5, 25, 0, 2000]]\n",
      "------------------------------\n",
      "THE BOXES IN REGION #1 ARE [[-75, -70, -90, -85, 0, 2000], [-75, -70, -85, -80, 0, 2000], [-75, -70, -80, -75, 0, 2000], [-75, -70, -75, -70, 0, 2000], [-75, -70, -70, -65, 0, 2000], [-75, -70, -65, -60, 0, 2000], [-75, -70, -60, -55, 0, 2000], [-75, -70, -55, -50, 0, 2000], [-70, -65, -90, -85, 0, 2000], [-70, -65, -85, -80, 0, 2000], [-70, -65, -80, -75, 0, 2000], [-70, -65, -75, -70, 0, 2000], [-70, -65, -70, -65, 0, 2000], [-70, -65, -65, -60, 0, 2000], [-70, -65, -60, -55, 0, 2000], [-70, -65, -55, -50, 0, 2000], [-65, -60, -90, -85, 0, 2000], [-65, -60, -85, -80, 0, 2000], [-65, -60, -80, -75, 0, 2000], [-65, -60, -75, -70, 0, 2000], [-65, -60, -70, -65, 0, 2000], [-65, -60, -65, -60, 0, 2000], [-65, -60, -60, -55, 0, 2000], [-65, -60, -55, -50, 0, 2000], [-60, -55, -90, -85, 0, 2000], [-60, -55, -85, -80, 0, 2000], [-60, -55, -80, -75, 0, 2000], [-60, -55, -75, -70, 0, 2000], [-60, -55, -70, -65, 0, 2000], [-60, -55, -65, -60, 0, 2000], [-60, -55, -60, -55, 0, 2000], [-60, -55, -55, -50, 0, 2000], [-55, -50, -90, -85, 0, 2000], [-55, -50, -85, -80, 0, 2000], [-55, -50, -80, -75, 0, 2000], [-55, -50, -75, -70, 0, 2000], [-55, -50, -70, -65, 0, 2000], [-55, -50, -65, -60, 0, 2000], [-55, -50, -60, -55, 0, 2000], [-55, -50, -55, -50, 0, 2000], [-50, -45, -90, -85, 0, 2000], [-50, -45, -85, -80, 0, 2000], [-50, -45, -80, -75, 0, 2000], [-50, -45, -75, -70, 0, 2000], [-50, -45, -70, -65, 0, 2000], [-50, -45, -65, -60, 0, 2000], [-50, -45, -60, -55, 0, 2000], [-50, -45, -55, -50, 0, 2000], [-45, -40, -90, -85, 0, 2000], [-45, -40, -85, -80, 0, 2000], [-45, -40, -80, -75, 0, 2000], [-45, -40, -75, -70, 0, 2000], [-45, -40, -70, -65, 0, 2000], [-45, -40, -65, -60, 0, 2000], [-45, -40, -60, -55, 0, 2000], [-45, -40, -55, -50, 0, 2000], [-40, -35, -90, -85, 0, 2000], [-40, -35, -85, -80, 0, 2000], [-40, -35, -80, -75, 0, 2000], [-40, -35, -75, -70, 0, 2000], [-40, -35, -70, -65, 0, 2000], [-40, -35, -65, -60, 0, 2000], [-40, -35, -60, -55, 0, 2000], [-40, -35, -55, -50, 0, 2000]]\n",
      "------------------------------\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/argopy/data_fetchers/gdac_data.py:331: UserWarning: Found more than 50 files to load, this may take a while to process sequentially ! Consider using another data source (eg: 'erddap') or the 'parallel=True' option to improve processing time.\n",
      "  warnings.warn(\n",
      "/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/argopy/data_fetchers/gdac_data.py:331: UserWarning: Found more than 50 files to load, this may take a while to process sequentially ! Consider using another data source (eg: 'erddap') or the 'parallel=True' option to improve processing time.\n",
      "  warnings.warn(\n",
      "/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/argopy/data_fetchers/gdac_data.py:331: UserWarning: Found more than 50 files to load, this may take a while to process sequentially ! Consider using another data source (eg: 'erddap') or the 'parallel=True' option to improve processing time.\n",
      "  warnings.warn(\n",
      "/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/argopy/data_fetchers/gdac_data.py:331: UserWarning: Found more than 50 files to load, this may take a while to process sequentially ! Consider using another data source (eg: 'erddap') or the 'parallel=True' option to improve processing time.\n",
      "  warnings.warn(\n",
      "/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/argopy/data_fetchers/gdac_data.py:331: UserWarning: Found more than 50 files to load, this may take a while to process sequentially ! Consider using another data source (eg: 'erddap') or the 'parallel=True' option to improve processing time.\n",
      "  warnings.warn(\n",
      "/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/argopy/data_fetchers/gdac_data.py:331: UserWarning: Found more than 50 files to load, this may take a while to process sequentially ! Consider using another data source (eg: 'erddap') or the 'parallel=True' option to improve processing time.\n",
      "  warnings.warn(\n",
      "/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/argopy/data_fetchers/gdac_data.py:331: UserWarning: Found more than 50 files to load, this may take a while to process sequentially ! Consider using another data source (eg: 'erddap') or the 'parallel=True' option to improve processing time.\n",
      "  warnings.warn(\n",
      "/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/argopy/data_fetchers/gdac_data.py:331: UserWarning: Found more than 50 files to load, this may take a while to process sequentially ! Consider using another data source (eg: 'erddap') or the 'parallel=True' option to improve processing time.\n",
      "  warnings.warn(\n",
      "/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/argopy/data_fetchers/gdac_data.py:331: UserWarning: Found more than 50 files to load, this may take a while to process sequentially ! Consider using another data source (eg: 'erddap') or the 'parallel=True' option to improve processing time.\n",
      "  warnings.warn(\n",
      "/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/argopy/xarray.py:944: UserWarning: None of the profiles can be interpolated (not reaching the requested depth range).\n",
      "  warnings.warn(\n",
      "/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/argopy/data_fetchers/gdac_data.py:331: UserWarning: Found more than 50 files to load, this may take a while to process sequentially ! Consider using another data source (eg: 'erddap') or the 'parallel=True' option to improve processing time.\n",
      "  warnings.warn(\n",
      "/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/argopy/data_fetchers/gdac_data.py:331: UserWarning: Found more than 50 files to load, this may take a while to process sequentially ! Consider using another data source (eg: 'erddap') or the 'parallel=True' option to improve processing time.\n",
      "  warnings.warn(\n",
      "/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/argopy/data_fetchers/gdac_data.py:331: UserWarning: Found more than 50 files to load, this may take a while to process sequentially ! Consider using another data source (eg: 'erddap') or the 'parallel=True' option to improve processing time.\n",
      "  warnings.warn(\n",
      "/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/numpy/core/fromnumeric.py:59: RuntimeWarning: overflow encountered in multiply\n",
      "  return bound(*args, **kwds)\n",
      "/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/argopy/data_fetchers/gdac_data.py:331: UserWarning: Found more than 50 files to load, this may take a while to process sequentially ! Consider using another data source (eg: 'erddap') or the 'parallel=True' option to improve processing time.\n",
      "  warnings.warn(\n",
      "/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/argopy/data_fetchers/gdac_data.py:331: UserWarning: Found more than 50 files to load, this may take a while to process sequentially ! Consider using another data source (eg: 'erddap') or the 'parallel=True' option to improve processing time.\n",
      "  warnings.warn(\n",
      "/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/argopy/data_fetchers/gdac_data.py:331: UserWarning: Found more than 50 files to load, this may take a while to process sequentially ! Consider using another data source (eg: 'erddap') or the 'parallel=True' option to improve processing time.\n",
      "  warnings.warn(\n",
      "/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/argopy/data_fetchers/gdac_data.py:331: UserWarning: Found more than 50 files to load, this may take a while to process sequentially ! Consider using another data source (eg: 'erddap') or the 'parallel=True' option to improve processing time.\n",
      "  warnings.warn(\n",
      "/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/argopy/data_fetchers/gdac_data.py:331: UserWarning: Found more than 50 files to load, this may take a while to process sequentially ! Consider using another data source (eg: 'erddap') or the 'parallel=True' option to improve processing time.\n",
      "  warnings.warn(\n",
      "/home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/argopy/xarray.py:944: UserWarning: None of the profiles can be interpolated (not reaching the requested depth range).\n",
      "  warnings.warn(\n",
      "2025-01-03 09:09:46,631 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name=\"execute('get_box_delayed-cf148711-f2f2-43a3-ba97-2d89ea261e59')\" coro=<Worker.execute() done, defined at /home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/worker_state_machine.py:3609>> ended with CancelledError\n",
      "2025-01-03 09:09:46,708 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name=\"execute('get_box_delayed-4965b90e-c586-4263-83e8-d732ba79e06d')\" coro=<Worker.execute() done, defined at /home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/worker_state_machine.py:3609>> ended with CancelledError\n",
      "2025-01-03 09:09:46,709 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name=\"execute('get_box_delayed-fc8c48cb-62f6-4407-8543-941284b92c96')\" coro=<Worker.execute() done, defined at /home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/worker_state_machine.py:3609>> ended with CancelledError\n",
      "2025-01-03 09:09:46,709 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name=\"execute('get_box_delayed-7a70e616-9965-4882-a1a1-30037e214651')\" coro=<Worker.execute() done, defined at /home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/worker_state_machine.py:3609>> ended with CancelledError\n",
      "2025-01-03 09:09:46,709 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name=\"execute('get_box_delayed-3371b74e-3401-49ec-b1cd-0e1d5301ff2e')\" coro=<Worker.execute() done, defined at /home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/worker_state_machine.py:3609>> ended with CancelledError\n",
      "2025-01-03 09:09:46,710 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name=\"execute('get_box_delayed-9419ba25-8a33-4dd9-9d78-2477763f621e')\" coro=<Worker.execute() done, defined at /home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/worker_state_machine.py:3609>> ended with CancelledError\n",
      "2025-01-03 09:09:46,710 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name=\"execute('get_box_delayed-13d8e939-2f9d-4b04-9059-2bce2cc9348b')\" coro=<Worker.execute() done, defined at /home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/worker_state_machine.py:3609>> ended with CancelledError\n",
      "2025-01-03 09:09:46,719 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name=\"execute('get_box_delayed-71e3b365-d23f-4f25-89ce-0dd89fb79bd4')\" coro=<Worker.execute() done, defined at /home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/worker_state_machine.py:3609>> ended with CancelledError\n",
      "2025-01-03 09:09:46,719 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name=\"execute('get_box_delayed-44dc40c3-8d15-4a83-83e7-4c9e6c72eaf8')\" coro=<Worker.execute() done, defined at /home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/worker_state_machine.py:3609>> ended with CancelledError\n",
      "2025-01-03 09:09:46,720 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name=\"execute('get_box_delayed-0fbd208f-7f6d-48ce-b8dc-5d01a091cf44')\" coro=<Worker.execute() done, defined at /home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/worker_state_machine.py:3609>> ended with CancelledError\n",
      "2025-01-03 09:09:46,720 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name=\"execute('get_box_delayed-b310363f-09fc-4de0-a799-5168d592359a')\" coro=<Worker.execute() done, defined at /home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/worker_state_machine.py:3609>> ended with CancelledError\n",
      "2025-01-03 09:09:46,791 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name=\"execute('get_box_delayed-6bddf6f3-a996-4b96-82f8-03a1a27153f3')\" coro=<Worker.execute() done, defined at /home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/worker_state_machine.py:3609>> ended with CancelledError\n",
      "2025-01-03 09:09:46,791 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name=\"execute('get_box_delayed-ff91b525-b4e9-4095-9703-9a7f1d5e4e0d')\" coro=<Worker.execute() done, defined at /home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/worker_state_machine.py:3609>> ended with CancelledError\n",
      "2025-01-03 09:09:46,817 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name=\"execute('get_box_delayed-491d0537-bad3-4131-b783-a34c57d9530e')\" coro=<Worker.execute() done, defined at /home.ufs/amf2288/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/distributed/worker_state_machine.py:3609>> ended with CancelledError\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[12], line 5\u001b[0m\n\u001b[1;32m      3\u001b[0m target_step \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m5\u001b[39m\n\u001b[1;32m      4\u001b[0m interp_step \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m2\u001b[39m\n\u001b[0;32m----> 5\u001b[0m \u001b[43mget_target_box\u001b[49m\u001b[43m(\u001b[49m\u001b[43mbox\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mregion_step\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtarget_step\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43minterp_step\u001b[49m\u001b[43m)\u001b[49m\n",
      "Cell \u001b[0;32mIn[11], line 15\u001b[0m, in \u001b[0;36mget_target_box\u001b[0;34m(area, region_step, target_step, interp_step)\u001b[0m\n\u001b[1;32m     12\u001b[0m \u001b[38;5;28mprint\u001b[39m(text)\n\u001b[1;32m     13\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m-\u001b[39m\u001b[38;5;124m'\u001b[39m \u001b[38;5;241m*\u001b[39m \u001b[38;5;241m30\u001b[39m)\n\u001b[0;32m---> 15\u001b[0m errors \u001b[38;5;241m=\u001b[39m \u001b[43mget_box_dask\u001b[49m\u001b[43m(\u001b[49m\u001b[43mboxes\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43minterp_step\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     17\u001b[0m text \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mCOMPLETED REGION #\u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[38;5;124m OUT OF \u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;241m.\u001b[39mformat(n\u001b[38;5;241m+\u001b[39m\u001b[38;5;241m1\u001b[39m,\u001b[38;5;28mlen\u001b[39m(regions))\n\u001b[1;32m     18\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m-\u001b[39m\u001b[38;5;124m'\u001b[39m \u001b[38;5;241m*\u001b[39m \u001b[38;5;241m30\u001b[39m)\n",
      "Cell \u001b[0;32mIn[6], line 36\u001b[0m, in \u001b[0;36mget_box_dask\u001b[0;34m(boxes_list, interp_step)\u001b[0m\n\u001b[1;32m     33\u001b[0m tasks \u001b[38;5;241m=\u001b[39m [get_box_delayed(\u001b[38;5;241m*\u001b[39margs) \u001b[38;5;28;01mfor\u001b[39;00m args \u001b[38;5;129;01min\u001b[39;00m boxes_list]\n\u001b[1;32m     35\u001b[0m \u001b[38;5;66;03m# Compute the results in parallel\u001b[39;00m\n\u001b[0;32m---> 36\u001b[0m results \u001b[38;5;241m=\u001b[39m \u001b[43mdask\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mcompute\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mtasks\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     38\u001b[0m errors\u001b[38;5;241m=\u001b[39m[]\n\u001b[1;32m     40\u001b[0m \u001b[38;5;66;03m# Process the results as needed\u001b[39;00m\n",
      "File \u001b[0;32m~/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/site-packages/dask/base.py:660\u001b[0m, in \u001b[0;36mcompute\u001b[0;34m(traverse, optimize_graph, scheduler, get, *args, **kwargs)\u001b[0m\n\u001b[1;32m    657\u001b[0m     postcomputes\u001b[38;5;241m.\u001b[39mappend(x\u001b[38;5;241m.\u001b[39m__dask_postcompute__())\n\u001b[1;32m    659\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m shorten_traceback():\n\u001b[0;32m--> 660\u001b[0m     results \u001b[38;5;241m=\u001b[39m \u001b[43mschedule\u001b[49m\u001b[43m(\u001b[49m\u001b[43mdsk\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mkeys\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    662\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m repack([f(r, \u001b[38;5;241m*\u001b[39ma) \u001b[38;5;28;01mfor\u001b[39;00m r, (f, a) \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mzip\u001b[39m(results, postcomputes)])\n",
      "File \u001b[0;32m~/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/threading.py:655\u001b[0m, in \u001b[0;36mEvent.wait\u001b[0;34m(self, timeout)\u001b[0m\n\u001b[1;32m    653\u001b[0m signaled \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_flag\n\u001b[1;32m    654\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m signaled:\n\u001b[0;32m--> 655\u001b[0m     signaled \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_cond\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mwait\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtimeout\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    656\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m signaled\n",
      "File \u001b[0;32m~/mambaforge-pypy3/envs/Argo_Nov_24/lib/python3.12/threading.py:359\u001b[0m, in \u001b[0;36mCondition.wait\u001b[0;34m(self, timeout)\u001b[0m\n\u001b[1;32m    357\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m    358\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m timeout \u001b[38;5;241m>\u001b[39m \u001b[38;5;241m0\u001b[39m:\n\u001b[0;32m--> 359\u001b[0m         gotit \u001b[38;5;241m=\u001b[39m \u001b[43mwaiter\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43macquire\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43;01mTrue\u001b[39;49;00m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtimeout\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    360\u001b[0m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m    361\u001b[0m         gotit \u001b[38;5;241m=\u001b[39m waiter\u001b[38;5;241m.\u001b[39macquire(\u001b[38;5;28;01mFalse\u001b[39;00m)\n",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "source": [
    "box = [-75,25,-90,90,0,2000]\n",
    "region_step = 40\n",
    "target_step = 5\n",
    "interp_step = 2\n",
    "get_target_box(box, region_step, target_step, interp_step)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "cleint.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:Argo_Nov_24]",
   "language": "python",
   "name": "conda-env-Argo_Nov_24-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
